spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personsmanagement
    username: root
    password: haslo
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: true
    drop-first: true
